from typing import Protocol, Any, Dict, List, Optional


class PricingAgent(Protocol):
    def reset(self) -> None: ...
    def update_state(self, context: Dict[str, Any]) -> None: ...
    def select_action(self, context: Dict[str, Any]) -> Dict[str, Any]: ...
    def learn(self, transition: Dict[str, Any]) -> None: ...


class ChargingAgent(Protocol):
    def reset(self) -> None: ...
    def update_state(self, context: Dict[str, Any]) -> None: ...
    def select_action(self, vehicles: List[Any], context: Dict[str, Any]) -> Dict[str, Any]: ...
    def learn(self, transition: Dict[str, Any]) -> None: ...


class StorageAgent(Protocol):
    def reset(self) -> None: ...
    def update_state(self, context: Dict[str, Any]) -> None: ...
    def select_action(self, context: Dict[str, Any]) -> Dict[str, Any]: ...
    def learn(self, transition: Dict[str, Any]) -> None: ...


